tracing = false

[Connection]
proteusEndpoint = "join:50350"
DBEndpoint = "datastore:3306"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"
poolSize = 256
poolOverflow = 256

[Benchmark]
runtime = 120
doWarmup = true
warmup = 30
threadCount = 1
measuredsystem = "proteus"
workloadType = "simple"
targetLoad = 30
maxInFlightRead = 4
maxInFlightWrite = 4

[Operations]
writeRatio = 0.05
downVoteRatio = 0.1
distributionType = "uniform"

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 100
stories = 1000
comments = 1000

[GetMetrics]
[[GetMetrics.QPU]]
name = "dsdriver"
endpoint = "dsdriver:50150"
[[GetMetrics.QPU]]
name = "sum"
endpoint = "sum:50250"
[[GetMetrics.QPU]]
name = "join"
endpoint = "join:50350"

[Distributions]
[[Distributions.VotesPerStory]]
bin = 0
count = 995
[[Distributions.VotesPerStory]]
bin = 10
[[Distributions.VotesPerStory]]
bin = 5000
count = 5

[[Distributions.VotesPerComment]]
bin = 0
count = 741
[[Distributions.VotesPerComment]]
bin = 10
count = 228
[[Distributions.VotesPerComment]]
bin = 20
count = 23
[[Distributions.VotesPerComment]]
bin = 30
count = 5
[[Distributions.VotesPerComment]]
bin = 40
count = 2
[[Distributions.VotesPerComment]]
bin = 50
count = 1

[[Distributions.CommentsPerStory]]
bin = 0
count = 836
[[Distributions.CommentsPerStory]]
bin = 10
count = 119
[[Distributions.CommentsPerStory]]
bin = 20
count = 25
[[Distributions.CommentsPerStory]]
bin = 30
count = 10
[[Distributions.CommentsPerStory]]
bin = 40
count = 5
[[Distributions.CommentsPerStory]]
bin = 50
count = 3
[[Distributions.CommentsPerStory]]
bin = 60
count = 1
[[Distributions.CommentsPerStory]]
bin = 70
count = 1
