tracing = false

[Connection]
proteusEndpoint = "join:50350"
DBEndpoint = "datastore:3306"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"
poolSize = 256
poolOverflow = 256

[Benchmark]
runtime = 120
doWarmup = true
warmup = 30
threadCount = 1
measuredsystem = "proteus"
workloadType = "simple"
targetLoad = 30
maxInFlightRead = 4
maxInFlightWrite = 4

[Operations]
writeRatio = 0.05
downVoteRatio = 0.1
voteTopStories = false

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 100
stories = 1000
comments = 1000

[GetMetrics]
[[GetMetrics.QPU]]
name = "dsdriver"
endpoint = "dsdriver:50150"
[[GetMetrics.QPU]]
name = "sum"
endpoint = "sum:50250"
[[GetMetrics.QPU]]
name = "join"
endpoint = "join:50350"
