tracing = false

[Connection]
endpoint = "127.0.0.1:3307"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"

[Benchmark]
opCount = 1000000
runtime = 120
doWarmup = true
warmup = 30
threadCount = 1
measuredsystem = "proteus"

[Operations]
writeRatio = 0.0
downVoteRatio = 0.2

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 10
stories = 1000
comments = 10
storyVotes = 1000
