tracing = false

[Connection]
proteusEndpoint = "127.0.0.1:50350"
DBEndpoint = "127.0.0.1:3309"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"
poolSize = 256
poolOverflow = 256

[Benchmark]
runtime = 20
doWarmup = false
warmup = 10
threadCount = 1
# measuredSystem = "proteus"
measuredSystem = "mysql"
workloadType = "simple"
targetLoad = 10
maxInFlightRead = 1
maxInFlightWrite = 1

[Operations]
writeRatio = 0.05
downVoteRatio = 0.2

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 100
stories = 1000
comments = 1000
votes = 1000
