tracing = false

[Connection]
proteusEndpoint = "127.0.0.1:50350"
DBEndpoint = "127.0.0.1:3307"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"

[Benchmark]
opCount = 100000
runtime = 20
doWarmup = true
warmup = 10
threadCount = 1
measuredSystem = "proteus"
targetLoad = 30
maxInFlight = 32

[Operations]
writeRatio = 0.0
downVoteRatio = 0.2

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 100
stories = 1000
comments = 1000
