tracing = false
workerPoolSize = 10
jobQueueSize = 1000
serverCount = 10

[Connection]
proteusEndpoint = "127.0.0.1:50350"
DBEndpoint = "127.0.0.1:3307"
database = "proteus_lobsters_db"
accessKeyID = "root"
secretAccessKey  = "verySecretPwd"
poolSize = 256
poolOverflow = 256

[Benchmark]
runtime = 20
doWarmup = false
warmup = 10
threadCount = 1
# measuredSystem = "proteus"
measuredSystem = "proteus"
workloadType = "simple"
targetLoad = 10
maxInFlightRead = 1
maxInFlightWrite = 1

[Operations]
writeRatio = 0.5
downVoteRatio = 0.2
distributionType = "uniform"

[Operations.Homepage]
storiesLimit = 5

[Preload.RecordCount]
users = 100
stories = 1000
comments = 1000
votes = 1000

[GetMetrics]
[[GetMetrics.QPU]]
name = "dsdriver"
endpoint = "127.0.0.1:50150"
[[GetMetrics.QPU]]
name = "sum"
endpoint = "127.0.0.1:50250"
[[GetMetrics.QPU]]
name = "join"
endpoint = "127.0.0.1:50350"

[Distributions]
[[Distributions.VotesPerStory]]
bin = 0
count = 995
[[Distributions.VotesPerStory]]
bin = 10
[[Distributions.VotesPerStory]]
bin = 5000
count = 5


[[Distributions.VotesPerComment]]
bin = 0
count = 741
[[Distributions.VotesPerComment]]
bin = 10
count = 228
[[Distributions.VotesPerComment]]
bin = 20
count = 23
[[Distributions.VotesPerComment]]
bin = 30
count = 5
[[Distributions.VotesPerComment]]
bin = 40
count = 2
[[Distributions.VotesPerComment]]
bin = 50
count = 1

[[Distributions.CommentsPerStory]]
bin = 0
count = 836
[[Distributions.CommentsPerStory]]
bin = 10
count = 119
[[Distributions.CommentsPerStory]]
bin = 20
count = 25
[[Distributions.CommentsPerStory]]
bin = 30
count = 10
[[Distributions.CommentsPerStory]]
bin = 40
count = 5
[[Distributions.CommentsPerStory]]
bin = 50
count = 3
[[Distributions.CommentsPerStory]]
bin = 60
count = 1
[[Distributions.CommentsPerStory]]
bin = 70
count = 1
